version: '3.7'

services:
  iverilog:
    image: lerwys/iverilog
    build:
      context: https://github.com/sergachev/docker-iverilog.git

  litex:
    image: lerwys/litex
    build:
      context: https://github.com/sergachev/docker-litex.git
    depends_on:
      - iverilog

  litex-env:
    image: lerwys/litex-env
    build:
      context: https://github.com/sergachev/docker-litex-env.git
    container_name: litex-env
    working_dir: /build
    environment:
        - XILINX_VIVADO={XIL_PATH:-/opt/Xilinx}/Vivado/${VIVADO_VER:-2019.1}
        - PATH=/yosys-bin:/opt/lm32/bin:/opt/riscv32im/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${XIL_PATH:-/opt/Xilinx}/Vivado/${VIVADO_VER:-2019.1}/bin
    privileged: true
    depends_on:
      - litex
      - riscv-tools
#      - lm32-tools
      - yosys
    volumes:
      - riscv-tools-volume:/opt/riscv32im:ro
#      - type: volume
#        source: lm32-tools-volume
#        target: /opt/lm32
#        volume:
#          read_only: true
      - yosys-volume-bin:/yosys-bin:ro
      - yosys-volume-share:/usr/local/share/yosys:ro
      - ${XIL_PATH:-/opt/Xilinx}:/opt/Xilinx:ro

  riscv-tools:
    image: lerwys/riscv-tools
    build:
      context: https://github.com/sergachev/docker-riscv-tools.git
    container_name: riscv-tools
    volumes:
      - type: volume
        source: riscv-tools-volume
        target: /opt/riscv32im
        volume:
          read_only: true

#  lm32-tools:
#    image: lerwys/lm32-tools
#    container_name: lm32-tools
#    volumes:
#      - type: volume
#        source: lm32-tools-volume
#        target: /opt/lm32
#        volume:
#          read_only: true

  yosys:
    image: yosys
    build:
      context: https://github.com/sergachev/docker-yosys.git
    container_name: yosys
    volumes:
     - yosys-volume-bin:/usr/local/bin:ro
     - yosys-volume-share:/usr/local/share/yosys:ro

volumes:
  riscv-tools-volume:
#  lm32-tools-volume:
  yosys-volume-bin:
  yosys-volume-share:
