version: '3.4'

services:

  litex-env:
    image: lerwys/litex-env
    container_name: litex-env
    working_dir: /build
    environment:
        - XILINX_VIVADO={XIL_PATH:-/opt/Xilinx}/Vivado/${VIVADO_VER:-2019.1}
        - PATH=/opt/lm32/bin:/opt/riscv32im/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${XIL_PATH:-/opt/Xilinx}/Vivado/${VIVADO_VER:-2019.1}/bin
    privileged: true
    depends_on:
      - riscv-tools
      - lm32-tools
    volumes:
      - type: volume
        source: riscv-tools-volume
        target: /opt/riscv32im
        volume:
          read_only: true
      - type: volume
        source: lm32-tools-volume
        target: /opt/lm32
        volume:
          read_only: true
      - type: bind
        source: ${XIL_PATH:-/opt/Xilinx}
        target: /opt/Xilinx
        volume:
          read_only: true

  riscv-tools:
    image: lerwys/riscv-tools
    container_name: riscv-tools
    volumes:
      - type: volume
        source: riscv-tools-volume
        target: /opt/riscv32im
        volume:
          read_only: true

  lm32-tools:
    image: lerwys/lm32-tools
    container_name: lm32-tools
    volumes:
      - type: volume
        source: lm32-tools-volume
        target: /opt/lm32
        volume:
          read_only: true

volumes:
  riscv-tools-volume:
  lm32-tools-volume:
